name: Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smp-feature: [ "", "smp" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build dockerfile
        run: docker build -t moss .
      # If all features are disabled
      - name: Run tests inside docker container
        if: ${{ matrix.smp-feature == '' }}
        run: |
          docker run moss "/bin/bash" -c "cargo run -r --no-default-features -- /bin/usertest" >> usertest.log
          docker run moss "/bin/bash" -c "cargo test -r --no-default-features" >> unittest.log
      # If any feature is enabled
      - name: Run tests inside docker container
        if: ${{ matrix.smp-feature == 'smp' }}
        run: |
          docker run moss "/bin/bash" -c "cargo run -r --no-default-features --features "${{ matrix.smp-feature }}" -- /bin/usertest" >> usertest.log
          docker run moss "/bin/bash" -c "cargo test -r --no-default-features --features "${{ matrix.smp-feature }}"" >> unittest.log
      - name: Display usertest output
        run: cat usertest.log
      - name: Display unit test output
        run: cat unittest.log
      - name: Check for usertest success line
        run: grep -q "All tests passed in " usertest.log || (echo "Usertests failed" && exit 1)
      - name: Check for unit test success line
        run: |
          grep -q "test result: .*ok.*\..*passed" unittest.log || (echo "Unit tests failed" && exit 1)
      - name: Upload usertest output as artifact
        uses: actions/upload-artifact@v6
        with:
          name: usertest-output-${{ matrix.smp-feature || 'up' }}
          path: usertest.log
      - name: Upload unittest output as artifact
        uses: actions/upload-artifact@v6
        with:
          name: unittest-output-${{ matrix.smp-feature || 'up' }}
          path: unittest.log
  upload-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build dockerfile
        run: docker build -t moss .
      - name: Run container
        run: docker run -d --name moss-container moss
      - name: Copy image file
        run: docker cp moss-container:/moss/moss.img moss.img
      - name: Upload image as artifact
        uses: actions/upload-artifact@v6
        with:
          name: moss.img
          path: moss.img
